### ISSUE TITLE
Typo in humidity sensor function generator

### ISSUE THREAD

**Issue by xEmkayx** [sensebox/React-Ardublockly#179]
The file [**sensebox-sensors.js**](https://github.com/sensebox/React-Ardublockly/blob/16c463508fc2d1d2658aebddbe3f8744732d8a45/src/components/Blockly/generator/sensebox-sensors.js#L443=) contains a typo, which leads to the program not compiling properly.

In line 443, instead of 
>      code = "airSensor.getHumidity()";
it says
>       code = "airSensor.getHumiditiy()";
Note the extra 'i' in Humidity.

This leads to following error:
```c
In function 'void loop()':
webserver_1:86:23: error: 'class SCD30' has no member named 'getHumiditiy'; did you mean 'getHumidity'?
      String(airSensor.getHumiditiy()) + String("%"))))))));
                       ^~~~~~~~~~~~
                       getHumidity
```

**Comment by mariopesch** [comment]
Thanks @xEmkayx for reporting! I just fixed it
