### ISSUE TITLE
Variables braking in Blockly

### ISSUE THREAD

**Issue by Crazyroostereye1** [sensebox/React-Ardublockly#192]
When using the variable Block, the Variable name in the Source Code is initialized as what I set, but when using it in a if statement or similar It becomes changed. Example the integer _test_ becomes _r_N_4ozC7mV_JG_5BM_25_5Euu_ . 

![Screenshot from 2022-10-22 13-42-54](https://user-images.githubusercontent.com/63781667/197337095-3dfc0ee8-13fb-45d0-b4ee-eff416e55cf2.png)

**Comment by mariopesch** [comment]
@Crazyroostereye1 thanks for reporting! Should be fixed via #193

**Comment by Crazyroostereye1** [comment]
change x by Number still has the Issue
![image](https://user-images.githubusercontent.com/63781667/198559246-59d1fc8f-eab1-4aa2-bfba-0475d5590709.png)
