### ISSUE TITLE
[Blockly][Codegenerator] Allow openSenseMap Block without Interval Block around

### ISSUE THREAD

**Issue by mariopesch** [sensebox/React-Ardublockly#255]
### Block description
Currently the openSenseMap Block needs to be nested inside the interval block. When using other structures such as the case structure the interval block is not needed

**Comment by Thiemann96** [comment]
I mean [a825b1d](https://github.com/sensebox/React-Ardublockly/commit/a825b1d1e6b14edf394183c3c67c5b570c20cb75) works but ulitmately I am not sure if this is the correct way. Was not really able to figure out where `LOOP_TYPES` is defined

**Comment by mariopesch** [comment]
@Thiemann96 see here: https://github.com/sensebox/React-Ardublockly/pull/246/commits/85c7dacec76cc99a1cba2b5ef7175d9d2845458c one can just add more blocks to the LOOP_TYPES
