### ISSUE TITLE
[Blockly][Codegenerator] CHange SMT50 code for MCU-S2

### ISSUE THREAD

**Issue by Thiemann96** [sensebox/React-Ardublockly#311]
Change SMT50 code for the MCU-S2 to; 
```c++
float getSMT50Temperature(int analogPin){
  float voltage = analogReadMilliVolts(analogPin)/1000.0;
   return (voltage - 0.5) * 100;
}
float getSMT50Moisture(int analogPin){
    float voltage = analogReadMilliVolts(analogPin)/1000.0;
   return (voltage * 50) / 3;
}
```
Additionally, set `analogReadResolution(12);` in the setup()

### Block description
Describe the current behaviour if the block already exist

### Expected block behaviour 
Describe how the block should work or which block should be added.

**Comment by janwirwahn** [comment]
function for soil moisture reading is linear only to 3V, according to SMT50 datasheet. set max value for voltage reading to 3.0V (or 50% volumetric water content)
```C
float getSMT50Moisture(int analogPin){ 
    float voltage = analogReadMilliVolts(analogPin)/1000.0;
    if (voltage >= 3) voltage = 3.0;   
    return (voltage * 50.0) / 3.0;
}
```
