### ISSUE TITLE
[Blockly][Codegenerator] Water temperature sensor

### ISSUE THREAD

**Issue by PaulaScharf** [sensebox/React-Ardublockly#316]
Water temperature sensor doesnt return its value.

Following blockly code:
![image](https://github.com/sensebox/React-Ardublockly/assets/48286621/288f75f8-55b7-429a-b86e-5cf8c46e6b2c)

results in following arduino code:
```
#include <senseBoxIO.h>
#include <OneWire.h> // http://librarymanager/All#OneWire
#include <DallasTemperature.h> // http://librarymanager/All#DallasTemperature


#define ONE_WIRE_BUS 1
OneWire oneWire(ONE_WIRE_BUS);
DallasTemperature sensors(&oneWire);

float getWaterTemp(){
sensors.requestTemperatures();
sensors.getTempCByIndex(0);
}




void setup() {
SerialUSB.begin(300);
sensors.begin();



}


void loop() {
SerialUSB.println(getWaterTemp());
delay(1000);

}
```

I think `getWaterTemp` needs to return sth or Im completely misunderstanding this code.

Also potentially for the MCU-S2 the pin needs to change from 1 to 3 (and 3 to 5 and 5 to 7)

**Comment by mariopesch** [comment]
Extension of this issue:

Update the block and allow reading multiple temperature sensors attached to one onewire adapter board. It's possible to hook up to 6 Sensors to one board.

**Comment by PaulaScharf** [comment]
dfrobot sensor doesnt work on old MCU because analogReadMilliVolts is used instead of analogRead
