### ISSUE TITLE
[Blockly][Codegenerator] Prevent use of space in variable names

### ISSUE THREAD

**Issue by mariopesch** [sensebox/React-Ardublockly#355]
### Block description

You can create variables with a space in the name such as:
<img width="215" alt="image" src="https://github.com/user-attachments/assets/79db6ff1-ece7-4699-84f2-6e9b8511c9e1">

The result is a compiler error.

### Expected block behaviour

Prevent the use of space in variable names. Either show an error during the creation process or automatically replace the space with an underscore.

**Comment by PaulaScharf** [comment]
Btw the issue also arises with other characters, not just spaces (" ' & * ...)

**Comment by mariopesch** [comment]
closed via #360
