### ISSUE TITLE
Custom MQTT Broker not working

### ISSUE THREAD

**Issue by felixerdy** [sensebox/React-Ardublockly#64]
You cannot change the MQTT Broker when using the `Connect to MQTT Broker` block. As you can see in the video below, changes are not applied.

https://user-images.githubusercontent.com/12086004/107620438-f9447d00-6c54-11eb-9832-91bbffee440d.mov

This also applies to the `port`, but `username` and `password` are working

**Comment by mariopesch** [comment]
Thanks @felixerdy I'll check it

**Comment by felixerdy** [comment]
And, as a follow up, `temperature` in the function `Adafruit_MQTT_Publish` should also be a string when using a custom MQTT Broker I guess. 

![Bildschirmfoto 2021-02-11 um 10 51 24](https://user-images.githubusercontent.com/12086004/107621841-2bef7500-6c57-11eb-8b55-77b88084340d.png)

not: `Adafruit_MQTT_Publish temperature = Adafruit_MQTT_Publish(&mqtt, temperature);`
but: `Adafruit_MQTT_Publish temperature = Adafruit_MQTT_Publish(&mqtt, "temperature");`

**Comment by mariopesch** [comment]
I'm also thinking about change the whole mqtt thing to the pubsub library instead of the adafruit library.
